version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: OnlineShopDbPostgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 006493
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    container_name: mongodb_cont
    expose:
      - 27017
    volumes:
      - mongo_data:/data/db

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mongodb
    ports:
      - "8080:8080"
    links:
      - postgres
      - mongodb

volumes:
  postgres_data:
  mongo_data:

  #    environment:
  #      SPRING_DATA_MONGODB_HOST: mongodb
  #      SPRING_DATA_MONGODB_PORT: 27017
  #      SPRING_DATA_MONGODB_REPOSITORIES_TYPE: auto
  #      SPRING_DATA_MONGODB_DATABASE: OnlineShopDb
  #
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/OnlineShopDbPostgres
  #      SPRING_DATASOURCE_USERNAME: postgres
  #      SPRING_DATASOURCE_PASSWORD: 006493
  #      SPRING_JPA_GENERATE-DDL: true